version: '3.7'
services:
  python_finops:
    image: finops
    ports:
      - "5000:5000"
    environment:
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

